# Generated by Django 5.0.2 on 2024-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_buyer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='bookname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='uploadimage',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
