# Generated by Django 5.0.2 on 2024-02-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_buyer_uploadimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='uploadimage',
            new_name='image',
        ),
    ]
